main: net.cybhd.vn.main.Main
name: vulkan
version: 2.6.5
api-version: 1.16
commands:
     l:
     vn:
     hub:
     eco:
     pay:
     tpa:
     msg:
     job:
     warp:
     mode:
     ping:
     shop:
     plot:
     home:
     clan:
     craft:
     stats:
     claim:
     login:
     lobby:
     select:
     target:
     report:
     vulkan:
     repair:
     auction:
     auktion:
     reports:
     sethome:
     tpdeny:
     tpaccept:
     unclaim:
     abilitys:
     rainbow:
     abilities: